create extension if not exists pgcrypto;
create type profile_status as enum ('DRAFT','PUBLISHED','PRIVATE','SUSPENDED');
create type plan_type as enum ('FREE','PREMIUM','VIP');
create table if not exists public.profiles(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,username text not null unique,display_name text,bio text,avatar_url text,banner_url text,status profile_status not null default 'DRAFT',plan plan_type not null default 'FREE',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.links(id uuid primary key default gen_random_uuid(),profile_id uuid not null references public.profiles(id) on delete cascade,title text not null,url text not null,description text,icon text,thumbnail_url text,position int not null default 0,enabled boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.social_links(id uuid primary key default gen_random_uuid(),profile_id uuid not null references public.profiles(id) on delete cascade,platform text not null,url text not null,position int not null default 0,enabled boolean not null default true);
create table if not exists public.modules(id uuid primary key default gen_random_uuid(),profile_id uuid not null references public.profiles(id) on delete cascade,type text not null,position int not null default 0,settings jsonb not null default '{}'::jsonb,enabled boolean not null default true);
create table if not exists public.music_tracks(id uuid primary key default gen_random_uuid(),profile_id uuid not null references public.profiles(id) on delete cascade,title text not null,artist text,audio_url text not null,cover_url text,autoplay_muted boolean not null default false,loop boolean not null default false);
create index if not exists profiles_username_idx on public.profiles(username);
create index if not exists links_profile_idx on public.links(profile_id,position);
create index if not exists socials_profile_idx on public.social_links(profile_id,position);
create index if not exists modules_profile_idx on public.modules(profile_id,position);
alter table public.profiles enable row level security;
alter table public.links enable row level security;
alter table public.social_links enable row level security;
alter table public.modules enable row level security;
alter table public.music_tracks enable row level security;
create policy "public profiles are readable when published" on public.profiles for select to anon,authenticated using (status='PUBLISHED');
create policy "owners manage profiles" on public.profiles for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);