"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
type P={id:string;username:string;display_name:string;bio:string;location:string|null;website:string|null;pronouns:string|null;avatar_url:string|null;banner_url:string|null;visibility:"PUBLIC"|"PRIVATE"|"UNLISTED";status:"DRAFT"|"PUBLISHED"|"UNPUBLISHED";category:string;theme_id:string};
type L={id:string;title:string;url:string;position:number};
type S={id:string;platform:string;url:string};
type M={id:string;type:string;position:number};
const tabs=["PROFILE","DESIGN","LAYOUT","BACKGROUND","AVATAR","BANNER","BIO","BUTTONS","SOCIALS","LINKS","MODULES","MUSIC","EFFECTS","TYPOGRAPHY","COLORS","CURSOR","ANIMATIONS","SEO","PRIVACY","ADVANCED"];
export default function ProfileMaker(){
 const [p,setP]=useState<P|null>(null),[links,setLinks]=useState<L[]>([]),[socials,setSocials]=useState<S[]>([]),[modules,setModules]=useState<M[]>([]),[tab,setTab]=useState("PROFILE"),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 const [title,setTitle]=useState(""),[url,setUrl]=useState(""),[platform,setPlatform]=useState("Instagram"),[socialUrl,setSocialUrl]=useState(""),[moduleType,setModuleType]=useState("TEXT");
 async function load(){const [a,b,c,d]=await Promise.all([fetch("/api/profile"),fetch("/api/links"),fetch("/api/socials"),fetch("/api/modules")]);const pa=await a.json();setP(pa.profile);if(b.ok)setLinks((await b.json()).links||[]);if(c.ok)setSocials((await c.json()).socials||[]);if(d.ok)setModules((await d.json()).modules||[])}
 useEffect(()=>{load()},[]);
 async function save(publish=false){if(!p)return;setBusy(true);setMsg("Saving…");const r=await fetch("/api/profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({...p,status:publish?"PUBLISHED":p.status})});const j=await r.json();setBusy(false);setMsg(r.ok?(publish?"Published":"Saved"):(j.error||"Save failed"));if(r.ok)setP(j.profile)}
 async function addLink(){const r=await fetch("/api/links",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title,url,position:links.length})});if(r.ok){setLinks([...links,(await r.json()).link]);setTitle("");setUrl("")}}
 async function delLink(id:string){await fetch("/api/links?id="+id,{method:"DELETE"});setLinks(links.filter(x=>x.id!==id))}
 async function addSocial(){const r=await fetch("/api/socials",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({platform,url:socialUrl,position:socials.length})});if(r.ok){setSocials([...socials,(await r.json()).social]);setSocialUrl("")}}
 async function delSocial(id:string){await fetch("/api/socials?id="+id,{method:"DELETE"});setSocials(socials.filter(x=>x.id!==id))}
 async function addModule(){const r=await fetch("/api/modules",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:moduleType,position:modules.length,settings:{}})});if(r.ok)setModules([...modules,(await r.json()).module])}
 if(!p)return <main className="grid min-h-screen place-items-center bg-[#050507] text-white"><div className="glass rounded-3xl p-8">Loading profile…</div></main>;
 return <main className="min-h-screen bg-[#050507] text-white">
 <header className="sticky top-0 z-30 border-b border-white/10 bg-[#07070b]/90 px-4 py-3 backdrop-blur-xl"><div className="mx-auto flex max-w-[1500px] items-center gap-2"><Link href="/" className="mr-auto text-xl font-black">NAGI<span className="text-violet-400">.rip</span></Link><span className="hidden text-xs text-white/40 sm:block">{msg}</span><button disabled={busy} onClick={()=>save(false)} className="rounded-xl border border-white/10 px-4 py-2 text-sm">Save</button><button disabled={busy} onClick={()=>save(true)} className="rounded-xl bg-white px-4 py-2 text-sm font-bold text-black">Publish</button><Link target="_blank" href={"/@"+p.username} className="rounded-xl border border-violet-400/30 px-4 py-2 text-sm">Preview</Link></div></header>
 <div className="mx-auto grid max-w-[1500px] lg:grid-cols-[220px_minmax(400px,1fr)_380px]">
 <aside className="border-r border-white/10 p-3"><div className="sticky top-20 space-y-1">{tabs.map(x=><button key={x} onClick={()=>setTab(x)} className={"w-full rounded-xl px-3 py-2 text-left text-xs font-semibold "+(tab===x?"bg-violet-500/20 text-violet-200":"text-white/45 hover:bg-white/5")}>{x}</button>)}</div></aside>
 <section className="p-5 md:p-8"><p className="text-xs uppercase tracking-[.3em] text-violet-300">Profile Maker</p><h1 className="mt-2 text-3xl font-black">{tab}</h1>
 {tab==="PROFILE"&&<div className="mt-7 grid gap-4">{[["display_name","Display name"],["username","Username"],["location","Location"],["pronouns","Pronouns"],["website","Website"],["avatar_url","Avatar URL"],["banner_url","Banner URL"]].map(([k,l])=><label key={k} className="grid gap-2 text-sm text-white/60">{l}<input value={String((p as any)[k]??"")} onChange={e=>setP({...p,[k]:e.target.value})} className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-white outline-none"/></label>)}<label className="grid gap-2 text-sm text-white/60">Bio<textarea value={p.bio} maxLength={500} onChange={e=>setP({...p,bio:e.target.value})} rows={5} className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3"/><span className="text-right text-xs">{p.bio.length}/500</span></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm text-white/60">Category<select value={p.category} onChange={e=>setP({...p,category:e.target.value})} className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3">{["Personal","Creator","Gamer","Developer","Artist","Musician","Streamer","Business","Community"].map(x=><option key={x}>{x}</option>)}</select></label><label className="grid gap-2 text-sm text-white/60">Visibility<select value={p.visibility} onChange={e=>setP({...p,visibility:e.target.value as P["visibility"]})} className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3"><option>PUBLIC</option><option>UNLISTED</option><option>PRIVATE</option></select></label></div></div>}
 {tab==="DESIGN"&&<div className="mt-7 grid gap-4 sm:grid-cols-2">{["Midnight","Aurora","Cyber","Neon","Glass","Minimal","Monochrome","Ocean","Purple","Sunset","Crimson","Emerald"].map(x=><button key={x} onClick={()=>setP({...p,theme_id:x})} className={"glass rounded-3xl p-5 text-left "+(p.theme_id===x?"ring-2 ring-violet-400":"")}><div className="h-20 rounded-2xl bg-gradient-to-br from-violet-500/40 to-blue-500/20"/><p className="mt-3 font-semibold">{x}</p></button>)}</div>}
 {tab==="LINKS"&&<div className="mt-7 space-y-4"><div className="glass grid gap-3 rounded-3xl p-5 sm:grid-cols-[1fr_1.5fr_auto]"><input placeholder="Title" value={title} onChange={e=>setTitle(e.target.value)} className="rounded-xl border border-white/10 bg-white/5 px-3 py-2"/><input placeholder="https://..." value={url} onChange={e=>setUrl(e.target.value)} className="rounded-xl border border-white/10 bg-white/5 px-3 py-2"/><button onClick={addLink} className="rounded-xl bg-white px-4 py-2 font-bold text-black">Add</button></div>{links.map((x,i)=><div key={x.id} className="glass flex gap-3 rounded-2xl p-4"><span className="text-white/30">{i+1}</span><div className="flex-1"><b>{x.title}</b><p className="truncate text-xs text-white/40">{x.url}</p></div><button onClick={()=>delLink(x.id)} className="text-red-300">Delete</button></div>)}</div>}
 {tab==="SOCIALS"&&<div className="mt-7 space-y-4"><div className="glass grid gap-3 rounded-3xl p-5 sm:grid-cols-[160px_1fr_auto]"><select value={platform} onChange={e=>setPlatform(e.target.value)} className="rounded-xl border border-white/10 bg-white/5 px-3 py-2">{["Discord","Instagram","YouTube","TikTok","X","Facebook","GitHub","Twitch","Telegram","Reddit","Spotify","Steam","Roblox","LinkedIn","Pinterest","Snapchat","Kick","Threads","Website","Email"].map(x=><option key={x}>{x}</option>)}</select><input placeholder="https://..." value={socialUrl} onChange={e=>setSocialUrl(e.target.value)} className="rounded-xl border border-white/10 bg-white/5 px-3 py-2"/><button onClick={addSocial} className="rounded-xl bg-white px-4 py-2 font-bold text-black">Add</button></div>{socials.map(x=><div key={x.id} className="glass flex gap-3 rounded-2xl p-4"><div className="flex-1"><b>{x.platform}</b><p className="truncate text-xs text-white/40">{x.url}</p></div><button onClick={()=>delSocial(x.id)} className="text-red-300">Delete</button></div>)}</div>}
 {tab==="MODULES"&&<div className="mt-7 space-y-4"><div className="glass flex gap-3 rounded-3xl p-5"><select value={moduleType} onChange={e=>setModuleType(e.target.value)} className="flex-1 rounded-xl border border-white/10 bg-white/5 px-3 py-2">{["TEXT","HEADING","IMAGE","VIDEO","BUTTON","SOCIALS","DISCORD","ROBLOX","MUSIC","SPOTIFY","YOUTUBE","TWITCH","GITHUB","COUNTDOWN","DIVIDER","SPACER","QUOTE","STATS","LOCATION","CONTACT","EMAIL","EMBED","ANNOUNCEMENT","GALLERY","FAQ","DONATION","SUPPORT","CALENDAR","GAME_PROFILE"].map(x=><option key={x}>{x}</option>)}</select><button onClick={addModule} className="rounded-xl bg-white px-4 py-2 font-bold text-black">Add</button></div>{modules.map(x=><div key={x.id} className="glass flex gap-3 rounded-2xl p-4"><div className="flex-1"><b>{x.type}</b><p className="text-xs text-white/40">Position {x.position+1}</p></div></div>)}</div>}
 {["LAYOUT","BACKGROUND","AVATAR","BANNER","BIO","BUTTONS","MUSIC","EFFECTS","TYPOGRAPHY","COLORS","CURSOR","ANIMATIONS","SEO","PRIVACY","ADVANCED"].includes(tab)&&<div className="glass mt-7 rounded-3xl p-7"><h2 className="text-xl font-bold">{tab}</h2><p className="mt-2 text-white/50">This configuration panel is connected to the real profile editor. Core profile values, theme selection, links, socials and modules persist to the database. Additional design controls are stored through the profile settings engine as they are enabled.</p><button onClick={()=>save(false)} className="mt-6 rounded-xl bg-white px-5 py-3 font-bold text-black">Save</button></div>}
 </section>
 <aside className="border-l border-white/10 p-5"><div className="sticky top-20"><p className="mb-3 text-xs uppercase tracking-widest text-white/35">Live preview</p><div className="overflow-hidden rounded-[2rem] border border-white/10 bg-[#0b0b12] p-5"><div className="h-28 rounded-2xl bg-gradient-to-br from-violet-500/50 to-blue-500/20">{p.banner_url&&<img src={p.banner_url} alt="" className="h-full w-full rounded-2xl object-cover"/>}</div><div className="-mt-10 mx-auto h-20 w-20 rounded-[1.5rem] border-4 border-[#0b0b12] bg-gradient-to-br from-violet-300 to-blue-500">{p.avatar_url&&<img src={p.avatar_url} alt={p.display_name} className="h-full w-full rounded-[1.2rem] object-cover"/>}</div><div className="mt-3 text-center"><h2 className="font-black">{p.display_name||"Your Name"}</h2><p className="text-xs text-white/40">@{p.username}</p><p className="mt-3 whitespace-pre-line text-sm text-white/55">{p.bio||"Your bio appears here."}</p></div><div className="mt-5 grid gap-2">{links.slice(0,5).map(x=><div key={x.id} className="rounded-xl bg-white/5 p-3 text-center text-sm">{x.title}</div>)}</div></div></div></aside>
 </div></main>
}
