"use client";
import {useEffect,useState} from "react";
import Link from "next/link";

type Profile={id:string;username:string;display_name:string;bio:string;location:string|null;website:string|null;pronouns:string|null;status:"DRAFT"|"PUBLISHED"|"UNPUBLISHED"};
export default function ProfileEditor(){
 const [p,setP]=useState<Profile|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{fetch("/api/profiles").then(r=>r.json()).then(j=>{setP(j.profiles?.[0]??null);setLoading(false)}).catch(()=>setLoading(false))},[]);
 async function save(e:React.FormEvent){e.preventDefault();if(!p)return;setSaving(true);setMessage("");const r=await fetch("/api/profiles/"+p.id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({display_name:p.display_name,bio:p.bio,location:p.location??"",website:p.website??"",pronouns:p.pronouns??"",status:p.status})});const j=await r.json();setSaving(false);setMessage(r.ok?"Profile saved.":j.error??"Save failed.");if(r.ok)setP(j.profile)}
 if(loading)return <main className="min-h-screen bg-[#050507] p-8"><div className="mx-auto max-w-5xl animate-pulse rounded-3xl bg-white/5 p-12">Loading profile…</div></main>;
 if(!p)return <main className="min-h-screen bg-[#050507] p-8 text-white"><div className="mx-auto max-w-3xl glass rounded-3xl p-8"><h1 className="text-3xl font-black">Create your profile</h1><p className="mt-2 text-white/50">Your account is ready. Finish onboarding first.</p><Link href="/onboarding" className="mt-6 inline-block rounded-2xl bg-white px-5 py-3 font-semibold text-black">Start onboarding</Link></div></main>;
 return <main className="min-h-screen bg-[#050507] p-4 text-white md:p-8"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-violet-300">NAGI.rip Profile Maker</p><h1 className="mt-1 text-3xl font-black">@{p.username}</h1></div><div className="flex gap-2"><Link href={"/@"+p.username} className="rounded-xl border border-white/10 px-4 py-2">Preview</Link><form action="/api/auth/logout" method="post"><button className="rounded-xl border border-white/10 px-4 py-2">Logout</button></form></div></div>
 <div className="mt-8 grid gap-6 lg:grid-cols-[220px_1fr_360px]"><aside className="glass rounded-3xl p-4"><p className="mb-3 text-xs uppercase tracking-widest text-white/40">Profile Maker</p>{["PROFILE","DESIGN","LAYOUT","BACKGROUND","AVATAR","BANNER","BIO","BUTTONS","SOCIALS","LINKS","MODULES","MUSIC","EFFECTS","TYPOGRAPHY","COLORS","CURSOR","ANIMATIONS","SEO","PRIVACY","ADVANCED"].map(x=><div key={x} className={x==="PROFILE"?"rounded-xl bg-white/10 px-3 py-2 text-sm":"px-3 py-2 text-sm text-white/50"}>{x}</div>)}</aside>
 <form onSubmit={save} className="glass rounded-3xl p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Profile</h2><span className="text-sm text-white/45">{message}</span></div><div className="mt-6 space-y-4"><label className="block text-sm">Display name<input value={p.display_name} onChange={e=>setP({...p,display_name:e.target.value})} className="mt-2 w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3"/></label><label className="block text-sm">Bio<textarea value={p.bio} onChange={e=>setP({...p,bio:e.target.value})} maxLength={500} className="mt-2 min-h-32 w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3"/></label><div className="text-right text-xs text-white/35">{p.bio.length}/500</div><label className="block text-sm">Location<input value={p.location??""} onChange={e=>setP({...p,location:e.target.value})} className="mt-2 w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3"/></label><label className="block text-sm">Website<input value={p.website??""} onChange={e=>setP({...p,website:e.target.value})} placeholder="https://example.com" className="mt-2 w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3"/></label><label className="block text-sm">Pronouns<input value={p.pronouns??""} onChange={e=>setP({...p,pronouns:e.target.value})} className="mt-2 w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3"/></label><label className="block text-sm">Status<select value={p.status} onChange={e=>setP({...p,status:e.target.value as Profile["status"]})} className="mt-2 w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3"><option>DRAFT</option><option>UNPUBLISHED</option><option>PUBLISHED</option></select></label><button disabled={saving} className="w-full rounded-2xl bg-white py-3 font-semibold text-black disabled:opacity-50">{saving?"Saving…":"Save profile"}</button></div></form>
 <div className="glass rounded-3xl p-5"><p className="text-xs uppercase tracking-widest text-violet-300">Live preview</p><div className="mt-4 rounded-3xl bg-gradient-to-br from-violet-500/30 to-blue-500/20 p-6 text-center"><div className="mx-auto h-20 w-20 rounded-3xl bg-white/10"/><h3 className="mt-4 text-xl font-bold">{p.display_name||"Your name"}</h3><p className="text-sm text-white/40">@{p.username}</p><p className="mt-3 whitespace-pre-line text-sm text-white/60">{p.bio||"Your bio appears here."}</p><div className="mt-5 rounded-2xl bg-white/5 p-3 text-sm">Links will appear here</div></div></div></div></div></main>
}
