import { NextRequest,NextResponse } from "next/server";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
const schema=z.object({title:z.string().min(1).max(120),description:z.string().max(300).optional(),url:z.string().url().refine(u=>/^https?:$/i.test(new URL(u).protocol),{message:"Only http/https URLs are allowed"}),style:z.string().max(30).default("Glass"),position:z.number().int().min(0).default(0),enabled:z.boolean().default(true),open_new_tab:z.boolean().default(true),nofollow:z.boolean().default(false)});
async function ctx(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return {supabase,user:null,profile:null};const {data:profile}=await supabase.from("profiles").select("id").eq("user_id",user.id).maybeSingle();return {supabase,user,profile};}
export async function GET(){const {supabase,user,profile}=await ctx();if(!user||!profile)return NextResponse.json({error:"Unauthorized"},{status:401});const {data,error}=await supabase.from("links").select("*").eq("profile_id",profile.id).order("position");if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({links:data});}
export async function POST(req:NextRequest){const {supabase,user,profile}=await ctx();if(!user||!profile)return NextResponse.json({error:"Unauthorized"},{status:401});const parsed=schema.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Invalid link."},{status:400});const {data,error}=await supabase.from("links").insert({profile_id:profile.id,...parsed.data}).select("*").single();if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({link:data},{status:201});}
export async function PATCH(req:NextRequest){const {supabase,user,profile}=await ctx();if(!user||!profile)return NextResponse.json({error:"Unauthorized"},{status:401});const body=await req.json().catch(()=>null);const id=typeof body?.id==="string"?body.id:"";const parsed=schema.partial().safeParse(body);if(!id||!parsed.success)return NextResponse.json({error:"Invalid link."},{status:400});const {data,error}=await supabase.from("links").update(parsed.data).eq("id",id).eq("profile_id",profile.id).select("*").single();if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({link:data});}
export async function DELETE(req:NextRequest){const {supabase,user,profile}=await ctx();if(!user||!profile)return NextResponse.json({error:"Unauthorized"},{status:401});const id=new URL(req.url).searchParams.get("id");if(!id)return NextResponse.json({error:"Missing id."},{status:400});const {error}=await supabase.from("links").delete().eq("id",id).eq("profile_id",profile.id);if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({ok:true});}
